/**
 * The reference figure: a small anatomical diagram that shows, for any
 * result, WHERE on the body it applies.
 *
 * This is deliberately not an illustration. Every region is a lookup key, so
 * a result carrying a region name paints that region, and a result carrying
 * none paints nothing -- which is itself informative, because it says the
 * quantity is not localised.
 *
 * Geometry comes from `src/data/anatomy.json`, generated by
 * `scripts/extract-anatomy.mjs` from the template in public/anatomy. Only the
 * path outlines are used: the template's jQuery, PNG backdrops, and tooltip
 * machinery are all dropped, so this renders at any size with fill under our
 * control and costs 26 KB rather than 600 KB.
 */

import { useMemo } from "react";
import ANATOMY from "../data/anatomy.json";
import type { Theme } from "../theme";

interface AnatomyView {
  viewBox: number[];
  /** the template's photographic plate, relative to public/anatomy/ */
  image: string | null;
  paths: { id: string; region: string; d: string; label: string | null }[];
}

const VIEWS = ANATOMY as unknown as Record<"body" | "organs", AnatomyView>;

export type RegionName = string;

/** value per region, already normalised or not — see `domain` */
export type HeatMap = Record<RegionName, number>;

export interface AnatomyFigureProps {
  theme: Theme;
  /** region -> intensity. Regions absent from the map are drawn unfilled. */
  heat?: HeatMap;
  /** explicit [min,max]; defaults to the extent of `heat` */
  domain?: [number, number];
  /** regions to outline as selected, regardless of heat */
  selected?: RegionName[];
  view?: "body" | "organs";
  width?: number;
  height?: number;
  onPick?: (region: RegionName) => void;
  /** shown under the figure; keep it to a few words */
  caption?: string;
  /** unit for the tooltip value */
  unit?: string;
  /**
   * Draw the template's photographic plate behind the regions.
   *
   * Off by default: at thumbnail size the plate is illegible and competes
   * with the heat colours, and it costs ~230 KB per view. At the size the
   * sunburst centre or a dedicated panel gives it, it is what makes the
   * figure readable as anatomy rather than as an abstract outline.
   */
  backdrop?: boolean;
  /** opacity of that plate, when shown */
  backdropOpacity?: number;
}

/**
 * Region aliases.
 *
 * The template names regions as an illustrator would; results name them as
 * the anatomy or the rig does. Rather than rename the template (which would
 * silently break if it is ever regenerated) the mapping lives here, and
 * `resolveRegion` is the single place that knows about it.
 *
 * `elbow` is the template's own typo for `left-elbow` -- ana17 is
 * `right-elbow` and ana18 is its mirror. Renaming it in the JSON would make
 * the extract script's output disagree with its source.
 */
const ALIASES: Record<string, string> = {
  "left-elbow": "elbow",
  // common synonyms used by the circuit programs and the rigs
  shank: "right-leg",
  calf: "right-leg",
  "lower-leg": "right-leg",
  soleus: "right-leg",
  gastrocnemius: "right-leg",
  tibialis: "right-leg",
  quadriceps: "right-thigh",
  hamstring: "right-thigh",
  bicep: "right-arm",
  biceps: "right-arm",
  tricep: "right-arm",
  triceps: "right-arm",
  "upper-arm": "right-arm",
  hip: "pelvis",
  trunk: "chest",
  thorax: "chest",
  cortex: "brain",
  "motor-cortex": "brain",
  spine: "neck",
  "spinal-cord": "neck",
  cord: "neck",
  foot: "right-foot",
  ankle: "right-ankle",
  knee: "right-knee",
  thigh: "right-thigh",
  leg: "right-leg",
  arm: "right-arm",
  forearm: "right-forearm",
  hand: "right-hand",
  shoulder: "right-shoulder",
  wrist: "right-wrist",
};

/** Map a caller's region name onto a name the figure actually has. */
export function resolveRegion(name: string, view: "body" | "organs" = "body"): string | null {
  const key = name.trim().toLowerCase().replace(/[\s_]+/g, "-");
  const have = new Set(VIEWS[view].paths.map((p) => p.region));
  if (have.has(key)) return key;
  const alias = ALIASES[key];
  if (alias && have.has(alias)) return alias;
  // try the other view before giving up
  const other = view === "body" ? "organs" : "body";
  const otherHave = new Set(VIEWS[other].paths.map((p) => p.region));
  if (otherHave.has(key) || (alias && otherHave.has(alias))) return null;
  return null;
}

/** Which view a region name belongs to, or null if neither has it. */
export function viewOf(name: string): "body" | "organs" | null {
  const key = name.trim().toLowerCase().replace(/[\s_]+/g, "-");
  const alias = ALIASES[key] ?? key;
  for (const v of ["body", "organs"] as const) {
    if (VIEWS[v].paths.some((p) => p.region === alias)) return v;
  }
  return null;
}

export const allRegions = (view: "body" | "organs" = "body") =>
  VIEWS[view].paths.map((p) => p.region);

/** The template's own display label for a region, e.g. "RIGHT EYE". */
export function regionLabel(region: string): string | null {
  for (const v of ["body", "organs"] as const) {
    const hit = VIEWS[v].paths.find((p) => p.region === region);
    if (hit) return hit.label;
  }
  return null;
}

/**
 * Sequential colour ramp, cold to hot.
 *
 * Deliberately not a rainbow: rainbow ramps invent boundaries where the data
 * has none, which for a diagram whose whole job is "how much, and where"
 * would fabricate structure. This is a monotone-luminance ramp so ordering
 * survives greyscale printing.
 */
export function heatColour(t: number): string {
  const u = Math.max(0, Math.min(1, t));
  // dark blue -> teal -> amber -> red
  const stops: [number, number[]][] = [
    [0.0, [26, 40, 82]],
    [0.35, [30, 120, 140]],
    [0.65, [224, 160, 60]],
    [1.0, [193, 50, 45]],
  ];
  for (let i = 1; i < stops.length; i++) {
    if (u <= stops[i][0]) {
      const [p0, c0] = stops[i - 1];
      const [p1, c1] = stops[i];
      const f = (u - p0) / (p1 - p0 || 1);
      const c = c0.map((v, k) => Math.round(v + (c1[k] - v) * f));
      return `rgb(${c[0]},${c[1]},${c[2]})`;
    }
  }
  return `rgb(193,50,45)`;
}

export function AnatomyFigure({
  theme, heat, domain, selected, view = "body",
  width = 120, height = 200, onPick, caption, unit,
  backdrop = false, backdropOpacity = 0.55,
}: AnatomyFigureProps) {
  const v = VIEWS[view];

  // Resolve caller names once, so an unmapped name is dropped rather than
  // silently colouring nothing at render time.
  const resolved = useMemo(() => {
    const out = new Map<string, number>();
    for (const [name, value] of Object.entries(heat ?? {})) {
      if (!Number.isFinite(value)) continue;
      const r = resolveRegion(name, view);
      if (!r) continue;
      // A region can be named twice through aliases; keep the larger.
      out.set(r, Math.max(out.get(r) ?? -Infinity, value));
    }
    return out;
  }, [heat, view]);

  const [lo, hi] = useMemo(() => {
    if (domain) return domain;
    const vals = [...resolved.values()];
    if (!vals.length) return [0, 1] as [number, number];
    const a = Math.min(...vals);
    const b = Math.max(...vals);
    return (a === b ? [a - 1e-9, b] : [a, b]) as [number, number];
  }, [domain, resolved]);

  const sel = useMemo(
    () => new Set((selected ?? []).map((s) => resolveRegion(s, view)).filter(Boolean) as string[]),
    [selected, view],
  );

  const norm = (x: number) => (hi > lo ? (x - lo) / (hi - lo) : 0.5);

  return (
    <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 3 }}>
      <svg
        viewBox={v.viewBox.join(" ")}
        width={width}
        height={height}
        style={{ display: "block", overflow: "visible" }}
        role="img"
        aria-label={caption ?? "anatomical reference"}
      >
        {backdrop && v.image && (
          <image
            href={`${import.meta.env.BASE_URL}anatomy/${v.image}`}
            x={v.viewBox[0]}
            y={v.viewBox[1]}
            width={v.viewBox[2]}
            height={v.viewBox[3]}
            opacity={backdropOpacity}
            preserveAspectRatio="xMidYMid meet"
            // The plates are dark-on-dark photographs. On a dark panel they
            // sink into the background; lifting brightness and contrast makes
            // the anatomy legible without competing with the heat colours,
            // which sit above at 0.85 alpha.
            style={{ filter: "brightness(1.55) contrast(1.12)" }}
          />
        )}
        {v.paths.map((p) => {
          const value = resolved.get(p.region);
          const has = value !== undefined;
          const isSel = sel.has(p.region);
          return (
            <path
              key={p.id}
              d={p.d}
              fill={has ? heatColour(norm(value)) : "transparent"}
              fillOpacity={has ? 0.85 : 0}
              stroke={isSel ? theme.accent : has ? theme.border : theme.borderSoft ?? theme.border}
              strokeWidth={isSel ? 6 : 2}
              vectorEffect="non-scaling-stroke"
              style={{ cursor: onPick ? "pointer" : "default", transition: "fill-opacity 120ms" }}
              onClick={onPick ? () => onPick(p.region) : undefined}
            >
              <title>
                {p.label ?? p.region}
                {has ? `: ${fmt(value)}${unit ? " " + unit : ""}` : " (no value)"}
              </title>
            </path>
          );
        })}
      </svg>
      {caption && (
        <div style={{ fontSize: 8.5, color: theme.textMuted, textAlign: "center", maxWidth: width + 20, lineHeight: 1.3 }}>
          {caption}
        </div>
      )}
    </div>
  );
}

function fmt(v: number): string {
  if (v === 0) return "0";
  const a = Math.abs(v);
  if (a >= 1e4 || a < 1e-3) return v.toExponential(2);
  return v.toPrecision(4).replace(/\.?0+$/, "");
}

/** A compact legend for the ramp, for panels that show one. */
export function HeatLegend({ theme, lo, hi, unit, width = 110 }: {
  theme: Theme; lo: number; hi: number; unit?: string; width?: number;
}) {
  const stops = Array.from({ length: 24 }, (_, i) => i / 23);
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 2, width }}>
      <div style={{ display: "flex", height: 6, borderRadius: 2, overflow: "hidden" }}>
        {stops.map((t) => (
          <div key={t} style={{ flex: 1, background: heatColour(t) }} />
        ))}
      </div>
      <div style={{ display: "flex", justifyContent: "space-between", fontSize: 8, color: theme.textMuted, fontFamily: "monospace" }}>
        <span>{fmt(lo)}</span>
        <span>{unit}</span>
        <span>{fmt(hi)}</span>
      </div>
    </div>
  );
}
